version: "3"
services:
  sim:
    image: ghcr.io/pepperoni505/astrobee-krpc:astrobee_sim-base-3.0.0
    volumes:
      - "${XSOCK}:${XSOCK}:rw"
      - "${XAUTH}:${XAUTH}:rw"
      - "${pcd_dir}:/src/astrobee/src/simulation/pcd"
      - "${bootstrap_dir}:/tmp/bootstrap"
    environment:
      - "XAUTHORITY=${XAUTH}"
      - "DISPLAY"
    extra_hosts:
      - "hlp:10.42.0.36"
      - "mlp:10.42.0.35"
      - "llp:10.42.0.34"
    user: "astrobee"
    container_name: astrobee
    privileged: true
    network_mode: "host"
    entrypoint: /astrobee_init.sh bash /tmp/bootstrap/run.sh
  android-emulator:
    image: astrobee-android-sim
    volumes:
      - "${PWD}/../:/jebediah"
    extra_hosts:
      - "hlp:10.42.0.36"
      - "mlp:10.42.0.35"
      - "llp:10.42.0.34"
    entrypoint: bash /jebediah/scripts/entrypoint.sh
